// Code generated by paramgen. DO NOT EDIT.
// Source: github.com/ConduitIO/conduit-commons/tree/main/paramgen

package embed

import (
	"github.com/conduitio/conduit-commons/config"
)

const (
	ConfigCohereAuthSecretRef = "cohere.authSecretRef"
	ConfigInputField          = "inputField"
	ConfigMaxRetries          = "maxRetries"
	ConfigMaxTextsPerBatch    = "maxTextsPerBatch"
	ConfigModel               = "model"
	ConfigOllamaBaseURL       = "ollama.baseURL"
	ConfigOpenaiAuthSecretRef = "openai.authSecretRef"
	ConfigOpenaiBaseURL       = "openai.baseURL"
	ConfigOutputField         = "outputField"
	ConfigProvider            = "provider"
	ConfigRequestTimeout      = "requestTimeout"
	ConfigRetryBackoffFactor  = "retryBackoff.factor"
	ConfigRetryBackoffMax     = "retryBackoff.max"
	ConfigRetryBackoffMin     = "retryBackoff.min"
	ConfigVoyageAuthSecretRef = "voyage.authSecretRef"
)

func (Config) Parameters() map[string]config.Parameter {
	return map[string]config.Parameter{
		ConfigCohereAuthSecretRef: {
			Default:     "",
			Description: "CohereAuthSecretRef is the Cohere equivalent of OpenAIAuthSecretRef.\nNot yet implemented in this slice; see doc.go.",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{},
		},
		ConfigInputField: {
			Default:     ".Payload.After.text",
			Description: "InputField is the record field read as the text to embed. Default\n\".Payload.After.text\" matches the sibling chunk package's default\noutputField — the composable RAG record shape (design doc / RAG\ncontract) a chunk record carries its text under a named \"text\" field\nof a StructuredData payload, never raw bytes.",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{},
		},
		ConfigMaxRetries: {
			Default:     "5",
			Description: "MaxRetries bounds retry attempts for a rate-limited (429) or 5xx\nsub-batch call before it is failed with a coded\nai.embedding_provider_error (design doc §2, §7, Failure Modes §1).\nRetries never cross a sub-batch boundary and never widen a failed\nbatch into a partial success.",
			Type:        config.ParameterTypeInt,
			Validations: []config.Validation{
				config.ValidationGreaterThan{V: -1},
			},
		},
		ConfigMaxTextsPerBatch: {
			Default:     "96",
			Description: "MaxTextsPerBatch bounds how many records' texts are sent in a single\nhost-mediated embedding call. The processor sub-batches strictly\nwithin one Process call — never across calls, see doc.go — into as\nfew calls as this ceiling (clamped to the resolved provider's own\nper-request input limit) allows. Default 96 mirrors the core\nengine's built-in cohere.embed processor's MaxTextsPerRequest\ndefault and the design doc's §2 proposed default.",
			Type:        config.ParameterTypeInt,
			Validations: []config.Validation{
				config.ValidationGreaterThan{V: 0},
			},
		},
		ConfigModel: {
			Default:     "",
			Description: "Model is the provider-specific embedding model identifier, e.g.\n\"text-embedding-3-small\" for OpenAI. Required once a provider is\nresolved; validated in Config.Validate rather than here because the\nrequired-ness depends on which provider ends up selected.",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{},
		},
		ConfigOllamaBaseURL: {
			Default:     "",
			Description: "OllamaBaseURL, if set, makes \"ollama\" an auto-detection candidate\n(local Ollama has no API key) and overrides the ollama provider's\ndefault target, \"http://localhost:11434\" (Ollama's own documented\ndefault; used when \"ollama\" is explicitly selected but this field is\nleft empty). Must resolve within the pipeline's host-enforced egress\nallowlist — for a loopback/private target that means an explicit\n(IP,port) carve-out entry, not a bare hostname allowlist entry (see\nthe egress package's design doc).",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{},
		},
		ConfigOpenaiAuthSecretRef: {
			Default:     "",
			Description: "OpenAIAuthSecretRef names the host-managed secret holding the OpenAI\nAPI key. This is never the raw key value — per the egress package's\ndesign, credentials are host-injected as the Authorization header\nimmediately before dispatch and never enter guest memory. A\nnon-empty value here is also the auto-detection signal for \"openai\"\nas a resolution candidate (see ResolveProvider): the guest cannot\nsee whether an OPENAI_API_KEY-shaped environment variable is set\n(there is no such guest-visible credential), so candidacy is judged\non \"did the pipeline author configure a secret reference for this\nprovider\" instead.",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{},
		},
		ConfigOpenaiBaseURL: {
			Default:     "https://api.openai.com",
			Description: "OpenAIBaseURL overrides the OpenAI API base URL. Must resolve within\nthe pipeline's host-enforced egress allowlist or every call fails\nwith ai.embedding_host_not_allowed (host-side, design doc §1).",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{},
		},
		ConfigOutputField: {
			Default:     ".Payload.After.vector",
			Description: "OutputField is the record field the embedding vector is written to,\nas a native array (not a JSON-encoded byte string — see\nattachEmbedding). Default \".Payload.After.vector\" preserves the\noriginal text (InputField) alongside the vector in the same\nstructured record — this is also the field the pgvector destination\nreads by default (its own VectorField config defaults to \"vector\") —\nand is why this processor's OutputField and InputField default to\ntwo different subfields of the same StructuredData payload rather\nthan both overwriting the whole field. Set this explicitly to change\nwhere the vector lands.",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{},
		},
		ConfigProvider: {
			Default:     "",
			Description: "Provider explicitly selects the embedding provider (\"openai\",\n\"voyage\", \"cohere\", or \"ollama\"). If empty, resolution falls back to\nthe CONDUIT_EMBED_PROVIDER environment variable, then to\nauto-detecting exactly one configured provider — see ResolveProvider\nand the design doc's §2 resolution order.",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{},
		},
		ConfigRequestTimeout: {
			Default:     "30s",
			Description: "RequestTimeout bounds each individual host-mediated HTTP call.\nMirrors the design doc §2's proposed 30s per-attempt deadline.",
			Type:        config.ParameterTypeDuration,
			Validations: []config.Validation{},
		},
		ConfigRetryBackoffFactor: {
			Default:     "2",
			Description: "RetryBackoffFactor is the exponential backoff multiplier.",
			Type:        config.ParameterTypeFloat,
			Validations: []config.Validation{
				config.ValidationGreaterThan{V: 0},
			},
		},
		ConfigRetryBackoffMax: {
			Default:     "30s",
			Description: "RetryBackoffMax caps the exponential backoff wait between retries.",
			Type:        config.ParameterTypeDuration,
			Validations: []config.Validation{},
		},
		ConfigRetryBackoffMin: {
			Default:     "500ms",
			Description: "RetryBackoffMin is the minimum wait before the first retry, used\nwhen the provider response carries no Retry-After header.",
			Type:        config.ParameterTypeDuration,
			Validations: []config.Validation{},
		},
		ConfigVoyageAuthSecretRef: {
			Default:     "",
			Description: "VoyageAuthSecretRef is the Voyage AI equivalent of\nOpenAIAuthSecretRef. Slice 1 wires this into resolution and\nambiguity detection but the \"voyage\" provider itself is not yet\nimplemented — see doc.go's Slice 1 scope note.",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{},
		},
	}
}
