// Code generated by paramgen. DO NOT EDIT.
// Source: github.com/ConduitIO/conduit-commons/tree/main/paramgen

package chunk

import (
	"github.com/conduitio/conduit-commons/config"
)

const (
	ConfigChunkSize   = "chunkSize"
	ConfigInputField  = "inputField"
	ConfigOutputField = "outputField"
	ConfigOverlap     = "overlap"
	ConfigStrategy    = "strategy"
)

func (Config) Parameters() map[string]config.Parameter {
	return map[string]config.Parameter{
		ConfigChunkSize: {
			Default:     "1000",
			Description: "ChunkSize is the target maximum chunk size in Unicode characters\n(runes) — never bytes, see doc.go's \"offsets are runes, not bytes\"\nnote. fixed_size chunks are exactly ChunkSize runes, except the\nfinal one; sentence/recursive chunks are packed up to ChunkSize\nrunes without splitting below their strategy's natural boundary.\nDefault 1000 is an implementation-time constant (design doc §3\nleaves exact defaults unspecified) chosen as a size that comfortably\nholds a few paragraphs of prose — small enough for typical embedding\nmodel context limits, large enough to avoid over-fragmenting short\ndocuments.",
			Type:        config.ParameterTypeInt,
			Validations: []config.Validation{
				config.ValidationGreaterThan{V: 0},
			},
		},
		ConfigInputField: {
			Default:     ".Payload.After",
			Description: "InputField is the record field read as the text to chunk.",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{},
		},
		ConfigOutputField: {
			Default:     ".Payload.After.text",
			Description: "OutputField is the record field each chunk's text is written to on\nits output record. Default \".Payload.After.text\" writes the chunk's\ntext under a NAMED \"text\" field of a StructuredData payload — the\ncomposable RAG record shape (design doc / RAG contract): a chunk\nrecord's After is opencdc.StructuredData{\"text\": <chunk text>}, never\nraw bytes, so the sibling embed package's default inputField\n(\".Payload.After.text\") reads it directly, and so the embed\nprocessor's own default outputField (\".Payload.After.vector\") can add\nthe vector alongside this text field without clobbering it. Set this\nexplicitly (e.g. back to \".Payload.After\") if a pipeline needs the\nchunk text somewhere else.",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{},
		},
		ConfigOverlap: {
			Default:     "100",
			Description: "Overlap is the number of trailing runes from one chunk repeated at\nthe start of the next. Only meaningful for, and only honored by, the\nfixed_size strategy — see Config.Validate. sentence and recursive\nchunk on natural boundaries (sentences, paragraphs, words) and never\nrepeat content between chunks; a nonzero Overlap with those\nstrategies is accepted but ignored, not an error, so switching\nstrategies doesn't require also clearing this field. Default 100\nmirrors a common ~10% overlap for the default 1000-rune ChunkSize.",
			Type:        config.ParameterTypeInt,
			Validations: []config.Validation{
				config.ValidationGreaterThan{V: -1},
			},
		},
		ConfigStrategy: {
			Default:     "fixed_size",
			Description: "Strategy selects the chunking algorithm: \"fixed_size\", \"sentence\", or\n\"recursive\". See the package doc for what each one does.",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationInclusion{List: []string{"fixed_size", "sentence", "recursive"}},
			},
		},
	}
}
